services:
  stable-diffusion-webui:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    image: emsi/stable-diffusion-webui
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "7860"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ..:/stable-diffusion-webui
      - home:/root
    command: python3 launch.py --listen

volumes:
  home:
